-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- User Settings Table
create table if not exists user_settings (
  user_id bigint primary key, -- Discord User ID
  timezone text default 'UTC',
  daily_summary_time time,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Todos Table
create table if not exists todos (
  id bigint generated by default as identity primary key,
  user_id bigint not null references user_settings(user_id),
  content text not null,
  status text check (status in ('PENDING', 'COMPLETED', 'ARCHIVED')) default 'PENDING',
  due_date timestamp with time zone,
  priority int default 3, -- 1 (High) to 5 (Low)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Calendar Events Table
create table if not exists calendar_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references user_settings(user_id),
  title text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  location text,
  is_notified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Reminders Table
create table if not exists reminders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references user_settings(user_id),
  message text not null,
  remind_time timestamp with time zone not null,
  is_sent boolean default false,
  related_event_id bigint references calendar_events(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for performance
create index if not exists idx_todos_user_id on todos(user_id);
create index if not exists idx_calendar_events_user_id on calendar_events(user_id);
create index if not exists idx_reminders_user_id on reminders(user_id);
create index if not exists idx_reminders_remind_time on reminders(remind_time) where is_sent = false;

-- Provider Credentials Table
create table if not exists provider_credentials (
  user_id bigint not null references user_settings(user_id),
  provider_id text not null,
  credentials jsonb not null, -- Stores access_token, refresh_token, expires_at, etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, provider_id)
);

create index if not exists idx_provider_credentials_user_id on provider_credentials(user_id);
